on:
  pull_request:
    branches:
      - main

env:
  ENVIRONMENT: test

jobs:
  terraform:
    name: Terraform Plan
    runs-on: ubuntu-latest
    environment: test

    defaults:
      run:
        shell: bash
        working-directory: ./iac

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup TF version
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.6

      - name: Terraforv Init
        run: terraform init
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}

      - name: Terraform Plan
        run: terraform plan -var-file=$ENVIRONMENT.tfvars
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
